name: emlabEnv # packages needed to run amiris
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates
  - certifi
  - openssl
  - pip>=22.0
  - python=3.8
  - setuptools
  - sqlite
  - vc=14.2
  - vs2015_runtime
  - wheel
  - wincertstore
